#!/usr/bin/bash

UPDATE=0
NUMARG=0
FILTER=()

if ! [[ $* =~ --installroot ]]; then
	for arg do
		[[ ${arg:0:1} == - ]] && continue
		case "$arg" in
			(update|upgrade|up) UPDATE=1 ;;
			(*) break ;;
		esac
	done
fi

if [[ $UPDATE == 1 ]]; then
	for arg do
		[[ ${arg:0:1} == - ]] && continue

		if [[ $arg =~ ^zfs ]]; then
			printf -- '%b' \
				'use [1mzfs-update[22m ' \
				'to update zfs.\n'
			exit 1
		fi

		if [[ $arg =~ ^kernel ]]; then
			printf -- '%b' \
				'use [1mkernel-update[22m ' \
				'to update the kernel.\n'
			exit 1
		fi

		NUMARG=$(($NUMARG+1))
	done

	FILTER=('--exclude=kernel*')
	if ! [[ $* =~ --repo ]] && ! [[ $* =~ --repoid ]]; then
		FILTER+=('--disablerepo=zfs*')
	fi
fi

/usr/bin/dnf "${FILTER[@]}" "$@"
if [[ $? -eq 0 ]] && [[ $NUMARG -eq 1 ]] && [[ -t 1 ]]; then
	cat <<- 'END'

		zfs and kernel updates were excluded
		run [1mzfs-update[22m to update zfs
		run [1mkernel-update[22m to update the kernel

	END
fi
