#!/usr/bin/bash
# vim:set ts=3 sw=3:

shopt -s lastpipe

if [[ $(command -p id -u) != 0 ]]; then
	cat <<- END

		${0##*/} must be run as root.

	END
	exit 1
fi

if [[ -x /usr/bin/curl ]] && [[ -x /usr/bin/md5sum ]]; then
	printf -v UPSTREAM '%s' \
		https://raw.githubusercontent.com \
		/gregory-lee-bartholomew/fedora-on-zfs \
		/refs/heads/main/supplements/${0##*/}
	if [[ $(curl -s "$UPSTREAM" | md5sum) != $(cat "$0" | md5sum) ]]; then
		cat <<- END

			notice: differences detected between $0 and upstream
		END
	fi
fi

for arg; do [[ $arg =~ ^--refresh$ ]] && break; done

command -p dnf -q --repo=updates rq \
	--upgrades --queryformat="%{evr}.%{arch}\n" \
	kernel "${BASH_REMATCH[0]}" | read KERNEL

if [[ -z $KERNEL ]]; then
	printf 'No kernel updates found, aborting ...\n'
	exit 1
fi

rpm -q zfs | read ZFS

tr -d '\t' <<- CAUTION

	Kernel update [1mkernel-$KERNEL[22m is available.
	Your current version of OpenZFS is \
	[1m${ZFS:-[31munknown[39m}[22m.

	Before proceeding, check \
	[1mhttps://github.com/openzfs/zfs/releases[22m to veri-
	fy that your version of OpenZFS is compatible with this kernel update.

CAUTION
read -r -n 1 -p "Update to kernel-$KERNEL [y/n]?: " UPDATE
printf '\n'

if [[ $UPDATE != y ]]; then
	printf 'Update canceled.\n'
	exit 0
fi

command -p dnf -y --repo=updates update kernel\* || exit 1
rpm -q "kernel-$KERNEL" || exit 1

RETRIES=0
while ! lsinitrd -m -k "$KERNEL" 2> /dev/null | grep -qx 'zfs'; do
	RETRIES=$(($RETRIES+1))
	fmt -g 75 <<- ERROR

		ERROR: The zfs module does not appear to be in the updated initramfs.
		Without the zfs module, the new kernel+initramfs will not be able to
		boot your root-on-zfs system. You have a choice:

		1. Run [1mdnf history undo last[22m to undo this kernel update.

		2. Try running [1mdkms autoinstall ... && kernel-install add ...[22m
		This might suffice to fix situations where kernel-core was updated
		without using this script (try to avoid doing that).

		3. Exit now. (You can attempt to fix the problem manually with
		[1mdkms uninstall/install[22m and/or
		[1mkernel-install remove/add[22m.)

	ERROR
	read -r -n 1 -p "What is your choice [1/2/3]?: " CHOICE
	printf '\n'

	case "$CHOICE" in
		(1)
			command -p dnf history undo --skip-unavailable last
			exit 1
		;;
		(2)
			dkms autoupdate -k "$KERNEL"
			[[ $? == 0 ]] && kernel-install add \
				"$KERNEL" "/usr/lib/modules/$KERNEL/vmlinuz"
		;;
		(*) exit 1 ;;
	esac
done
if [[ $RETRIES -gt 0 ]]; then
	fmt -g 75 <<- INFO

		SUCCESS: Recovery option [1m$CHOICE[22m appears to have worked!

	INFO
fi
