#!/usr/bin/bash
# vim:set ts=3 sw=3:

set -e
shopt -s lastpipe

TARGET="$1"

# bold
function B {
	printf -- '[1m%s[22m' "$*"
}

# wrap lines
type -p fmt | read FORMAT || :
function FMT {
	if [[ -n $FORMAT ]]; then
		$FORMAT --width="${COLUMNS:-80}"
	else
		cat
	fi
}

if [[ -z $TARGET ]]; then
	FMT <<- END 1>&2

		$(B USAGE): ${0##*/} <target-filesystem>

	END
	exit 1
fi

if [[ $(zfs list -H -o mountpoint "$TARGET" 2> /dev/null) != / ]]; then
	FMT <<- END 1>&2

		$(B ERROR): $TARGET does not appear to be a root filesystem.

	END
	exit 1
fi

if [[ $TARGET == $(findmnt -n -o source /) ]]; then
	FMT <<- END 1>&2

		$(B ERROR): You cannot remove the running OS!

	END
	exit 1
fi

function prompt {
	ANSWER=''
	read -e -t 0.125 &> /dev/null || :
	local IFS=''
	while ! [[ $ANSWER =~ ^[yn]$ ]]; do
		printf "$* [y/n]: "
		read -r -n 1 ANSWER
		[[ $ANSWER != '' ]] && printf '\n'
	done
}

{
	zfs list -H -d 1 -o name "$TARGET"
	zfs list -H -r -o origin "${TARGET%%/*}" | grep "^$TARGET@"
} | readarray -t DESCENDANTS
if [[ ${#DESCENDANTS[@]} -gt 1 ]]; then
	FMT <<- END

		$(B WARNING): $TARGET appears to have descendant filesystems or
		clones. All decendants will be destroyed!

	END
	prompt "Do you want to proceed?"
	[[ $ANSWER == y ]] || exit 1
	echo
fi

read MID < /etc/machine-id
for boot in /boot $(ls -d /boot@[a-z] 2> /dev/null); do
	for conf in $boot/loader/entries/*.conf; do
		sed -n \
			-e '\%^machine-id\s% x;' \
			-e "\%^options\s.*root=zfs:$TARGET\(\s\|$\)% { \
				x; s/^\S\+\s\+//; T; p; \
			};" "$conf" | read id || continue
		if [[ $id =~ ^[[:xdigit:]]{32}$ ]] && [[ $id != $MID ]]; then
			rm -rf "$boot/$id" "$conf"
			sed -i "s/$id/$MID/" "$boot/loader/loader.conf" || :
		fi
	done
done

findmnt -n -o target "$TARGET" | xargs -r umount -l
zfs destroy -R "$TARGET"
