#!/usr/bin/bash
# vim:set ts=3 sw=3:

set -e
shopt -s lastpipe

TARGET="$1"

if [[ -z $TARGET ]]; then
	cat <<- END 1>&2

		USAGE: ${0##*/} <target-filesystem>

	END
	exit 1
fi

if [[ $(zfs list -H -o mountpoint "$TARGET" 2> /dev/null) != / ]]; then
	cat <<- END 1>&2

		ERROR: $TARGET does not appear to be a root filesystem.

	END
	exit 1
fi

if [[ $TARGET == $(findmnt -n -o source /) ]]; then
	cat <<- END 1>&2

		ERROR: You cannot remove the running OS!

	END
	exit 1
fi

function prompt {
        ANSWER=''
        read -e -t 0.125 &> /dev/null || :
        while ! [[ $ANSWER =~ ^[yn]$ ]]; do
                printf "$1 [y/n]: "
                read -r -n 1 ANSWER
                [[ $ANSWER != '' ]] && printf '\n'
        done
}

{
	zfs list -H -d 1 -o name "$TARGET"
	zfs list -H -r -o origin "${TARGET%%/*}" | grep "^$TARGET@"
} | readarray -t DESCENDANTS
if [[ ${#DESCENDANTS[@]} -gt 1 ]]; then
	cat  <<- END 1>&2

		WARNING: $TARGET appears to have descendant filesystems or
		clones. All decendants will be destroyed!

	END
	prompt "Do you want to proceed?"
	[[ $ANSWER == y ]] || exit 1
	echo
fi

read SELF < /etc/machine-id
for conf in /boot/loader/entries/*.conf; do
	sed -n \
		-e '\%^machine-id\s% x;' \
		-e "\%^options\s.*root=zfs:$TARGET\(\s\|$\)% { \
			x; s/^\S\+\s\+//; T; p; \
		};" "$conf" | read ID || continue
	if [[ $ID =~ ^[[:xdigit:]]{32}$ ]] && [[ $ID != $SELF ]]; then
		rm -rf "/boot/$ID" "$conf"
		sed -i "s/$ID/$SELF/" /boot/loader/loader.conf || :
	fi
done

findmnt -n -o target "$TARGET" | xargs -r umount -l
zfs destroy -R "$TARGET"
